### ISSUE TITLE
Hyperlink syntax?

### ISSUE THREAD

**Issue by arezzg** [aquakenzie/webgen#1]
Yeah, just read the title.

There is no section in the README mentioning how to define a hyperlink, let alone include it inside a paragraph, subsection, section or heading.

**Comment by kenziewebm** [comment]
the syntax is `.href url text` or `.link url text`
so `.href google.com this is a link too google.com` -> `<a href="google.com">this is a link to google.com</a>`

inside a paragraph:
(the blank line at the end is important - it marks the end of the paragraph)
```
.p this is a paragraph
.href archlinux.org it has a hyperlink
continuation of paragraph

```
![image](https://github.com/user-attachments/assets/65866ac4-79e3-45fc-ae7e-6adce5e686bb)

if you want a newline the `<br>` tag exists

there is currently no option to use two wg macros on one line, so youll have to write the `<a>` tag manually with sections, subsections, headers:
```
.s this is a <a href="gnu.org">hyperlinked</a> section
```
