### ISSUE TITLE
Inputting Outputting made easier?

### ISSUE THREAD

**Issue by arezzg** [aquakenzie/webgen#4]
Temporary (might make it permanent?) solution

We change the command syntax a bit and have it like this

```
webgen -i input.wg -o output.html
```

and if it is specified wrongly or not to our likings, we just fallback to the glorious `webgen input.wg > output.html`

Kinda like GPG and ASCII armor exporting?

**Comment by kenziewebm** [comment]
webgen is written in shell script
all modern shells support writing the output of a command to a file
there is no reason to make it more complicated
