### ISSUE TITLE
Dual suggestion

### ISSUE THREAD

**Issue by arezzg** [aquakenzie/webgen#6]
Hey.

It would be a fun and harmless task to unbreak the asterisk * sign.

People may want to list using asterisks or there might be other use cases so it would be cool to have bash not parse it.

alternative route, implement bullet lists; either as another feature, or to compensate for the lack of asterisk support, you know what happens when asterisks are listed in bash. they list everything.

**Comment by kenziewebm** [comment]
fixed by disabling globs
lists are planned (when i get around to doing it. maybe tomorrow or aftertomorrow
